// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pillsmaster.Persistence;

#nullable disable

namespace Pillsmaster.Persistence.Migrations
{
    [DbContext(typeof(PillsmasterDbContext))]
    partial class PillsmasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pillsmaster.Domain.Models.FoodStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodStatuses");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.MedicationDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CountPerTake")
                        .HasColumnType("float");

                    b.Property<int>("TakesPerDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MedicationDays");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveIngredientCount")
                        .HasColumnType("int");

                    b.Property<string>("InternationalName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PharmaTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PharmaTypeId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.PharmaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PharmaTypes");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("FoodStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnoughToFinish")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFoodDependent")
                        .HasColumnType("bit");

                    b.Property<Guid>("MedicationDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MedicineCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextTakeTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TakesCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserMedicineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FoodStatusId");

                    b.HasIndex("MedicationDayId");

                    b.HasIndex("PlanStatusId");

                    b.HasIndex("UserMedicineId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.PlanStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlanStatuses");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.Take", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TakeTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Takes");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("UserDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserDetailsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.UserDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.UserMedicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveIngredientCount")
                        .HasColumnType("int");

                    b.Property<string>("InternationalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PharmaTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PharmaTypeId");

                    b.ToTable("UserMedicines");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.Medicine", b =>
                {
                    b.HasOne("Pillsmaster.Domain.Models.PharmaType", "PharmaType")
                        .WithMany()
                        .HasForeignKey("PharmaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PharmaType");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.Plan", b =>
                {
                    b.HasOne("Pillsmaster.Domain.Models.FoodStatus", "FoodStatus")
                        .WithMany()
                        .HasForeignKey("FoodStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pillsmaster.Domain.Models.MedicationDay", "MedicationDay")
                        .WithMany()
                        .HasForeignKey("MedicationDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pillsmaster.Domain.Models.PlanStatus", "PlanStatus")
                        .WithMany()
                        .HasForeignKey("PlanStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pillsmaster.Domain.Models.UserMedicine", "UserMedicine")
                        .WithMany()
                        .HasForeignKey("UserMedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodStatus");

                    b.Navigation("MedicationDay");

                    b.Navigation("PlanStatus");

                    b.Navigation("UserMedicine");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.Take", b =>
                {
                    b.HasOne("Pillsmaster.Domain.Models.Plan", null)
                        .WithMany("Takes")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.User", b =>
                {
                    b.HasOne("Pillsmaster.Domain.Models.UserDetails", "UserDetails")
                        .WithMany()
                        .HasForeignKey("UserDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.UserMedicine", b =>
                {
                    b.HasOne("Pillsmaster.Domain.Models.PharmaType", "PharmaType")
                        .WithMany()
                        .HasForeignKey("PharmaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PharmaType");
                });

            modelBuilder.Entity("Pillsmaster.Domain.Models.Plan", b =>
                {
                    b.Navigation("Takes");
                });
#pragma warning restore 612, 618
        }
    }
}
